### PR TITLE
Website template reboot

### PR DESCRIPTION
**Pull request by techsouvik**
Changed the template for the website
<details>
<summary>
Home Page
</summary>
Screenshot 2021-09-10 at 9 53 05 PM
</details>
<details>
<summary>
Home Page (*members)
</summary>
Screenshot 2021-09-10 at 9 53 23 PM
</details>

### CODE REVIEW

**Comment by chaitak-gorai** [comment]
It seems good. For now, I am accepting the PR. There are some changes to do which I will add in the issue section.

**Comment by Dsantra92** [comment]
License was deleted. 🌚

**Comment by techsouvik** [comment]
will be adding the license within 3 days @Dsantra92

**Comment by Dsantra92** [comment]
Done.

**Pull request merged**
