### PR TITLE
Only Carousel texts are changed

### PR DESCRIPTION
**Pull request by techsouvik**
### Text on Carousels have been changed , no bugs

<details>
<summary>Carousel 1</summary>
Screenshot 2021-09-11 at 10 04 41 AM
</details>
<details>
Screenshot 2021-09-11 at 10 04 56 AM
<summary>Carousel 2</summary>
</details>
<details>
Screenshot 2021-09-11 at 10 05 23 AM
<summary>Carousel 3</summary>
</details>

### CODE REVIEW

**Comment by chaitak-gorai** [comment]
@techsouvik  can we change the background banner too. I think that will look great.

**Comment by techsouvik** [comment]
okkk
plss provide me 3 backgrounds
ok

**Comment by chaitak-gorai** [comment]
You can choose on your own. For reference use 
https://unsplash.com/

**Comment by techsouvik** [comment]
Okkk

**Pull request closed without merging**
